let startTime = toscalar(demo_make_series1 | summarize min(TimeStamp));
let endTime = toscalar(demo_make_series1 | summarize max(TimeStamp));
let binSize = 1d;
demo_make_series1
| where TimeStamp between (startTime .. endTime)
| make-series requests=count() default=0 on TimeStamp in range (startTime, endTime, binSize) by Country
| mv-expand TimeStamp to typeof(datetime), requests to typeof(int)
| project Country, requests, TimeStamp
| order by Country
