let startTime = toscalar(demo_make_series1 | summarize min(TimeStamp));
let endTime = toscalar(demo_make_series1 | summarize max(TimeStamp));
let binSize = 1h;
let windowSize = 10;
demo_make_series1
| where TimeStamp between (startTime .. endTime)
| where Country == "United States"
| make-series requests=count() default=0 on TimeStamp in range (startTime, endTime, binSize) by Country
| extend movingAverage = series_fir(requests, repeat(1, windowSize), true, true) 
| render timechart

