let startTime = toscalar(demo_make_series1 | summarize min(TimeStamp));
let endTime = toscalar(demo_make_series1 | summarize max(TimeStamp));
let binSize = 1h;
demo_make_series1
| where Country in ("United States", "Germany", "China")
| make-series requests=count() default=0 on TimeStamp from startTime to endTime step binSize by Country
| extend anomalies = series_decompose_anomalies(requests)
| render anomalychart with (anomalycolumns=anomalies)  

